services:
  server-db:
    ports:
      - 5433:5432
    expose:
      - 5433
    container_name: server_db_dev_container
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data